name: chatwoot_sdk
description: A flutter client sdk for chatwoot. Integrate Chatwoot flutter client into your flutter app and talk to your visitors/users in real time.
version: 0.0.1
homepage: https://github.com/omarfarouk228/chatwoot-flutter-sdk

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui:
  hive:
  hive_flutter:
  uuid:
  web_socket_channel:
  json_annotation:
  dio:
  equatable:
  riverpod:
  synchronized:
  intl:
  flutter_chat_types:
  stream_channel:
  async:
  webview_flutter:
  flutter_secure_storage:
  url_launcher:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  json_serializable:
  hive_generator:
  build_runner:
  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
